### ISSUE TITLE
node.js version

### ISSUE THREAD

**Issue by gforcada** [plone/plone.jenkins_node#2]
Right now when running this ansible playbook you are downloading the latest version of node.js: https://github.com/plone/plone.jenkins_node/blob/master/tasks/main.yml#L83

Shouldn't we stick to a specific version? Robotframework and its dependencies already showed us how unpredictable that can be if not pinned...

On top of that, this also means that different nodes could potentially end up with different versions, so free roam for jenkins jobs would not be possible if there are version problems.

**Comment by gforcada** [comment]
@thet @frapell which version of node.js are we supporting/expecting that works right now for Plone 5?

**Comment by frapell** [comment]
@gforcada right now, the Makefile for mockup behaves differently if node is < v0.11.x or not. I don't think we are expecting a specific version, but I would be +1 on pinning it. Maybe not to a specific version, but have a version at most current one.

We can update it in the future

**Comment by gforcada** [comment]
@frapell current stable version seems to be 0.12.3, could we pin to this one and revisit as time goes?

**Comment by frapell** [comment]
I would say yes. @vangheem what do you say?

**Comment by gforcada** [comment]
Whenever someone wants to change the version, just (re)open this issue.
